<?php
/** Doctors, CRM, patients, appointments, queue and clinical records. */
return [
    'up' => [

"CREATE TABLE doctors (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  name VARCHAR(120) NOT NULL,
  qualification VARCHAR(160) NULL,
  specialization VARCHAR(120) NULL,
  registration_number VARCHAR(60) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  consultation_fee DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  followup_fee DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  default_duration_minutes INT UNSIGNED NOT NULL DEFAULT 15,
  signature_path VARCHAR(255) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_doctor_org (organization_id, is_active),
  KEY idx_doctor_user (organization_id, user_id),
  CONSTRAINT fk_doctor_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT fk_doctor_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE doctor_branches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_doctor_branch (doctor_id, branch_id),
  KEY idx_db_org (organization_id, branch_id),
  CONSTRAINT fk_db_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  CONSTRAINT fk_db_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE doctor_schedules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NOT NULL,
  day_of_week TINYINT UNSIGNED NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  slot_minutes INT UNSIGNED NOT NULL DEFAULT 15,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_sched (organization_id, doctor_id, day_of_week),
  CONSTRAINT fk_sched_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  CONSTRAINT fk_sched_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE services (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(140) NOT NULL,
  code VARCHAR(40) NULL,
  category VARCHAR(60) NULL,
  description VARCHAR(255) NULL,
  price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  is_taxable TINYINT(1) NOT NULL DEFAULT 0,
  tax_percent DECIMAL(6,3) NOT NULL DEFAULT 0.000,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_service_org (organization_id, is_active),
  CONSTRAINT fk_service_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE patients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(26) NOT NULL,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NULL,
  patient_number VARCHAR(30) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  phone_normalized VARCHAR(20) NULL,
  alt_phone VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  dob DATE NULL,
  age_years INT UNSIGNED NULL,
  gender VARCHAR(20) NULL,
  blood_group VARCHAR(8) NULL,
  address VARCHAR(255) NULL,
  city VARCHAR(80) NULL,
  state VARCHAR(80) NULL,
  pin VARCHAR(12) NULL,
  emergency_contact_name VARCHAR(120) NULL,
  emergency_contact_phone VARCHAR(30) NULL,
  occupation VARCHAR(80) NULL,
  source VARCHAR(40) NULL,
  allergies TEXT NULL,
  medical_notes TEXT NULL,
  lead_id BIGINT UNSIGNED NULL,
  registered_at DATE NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_patient_number (organization_id, patient_number),
  UNIQUE KEY uq_patient_public (public_id),
  KEY idx_patient_phone (organization_id, phone_normalized),
  KEY idx_patient_name (organization_id, full_name),
  KEY idx_patient_branch (organization_id, branch_id),
  CONSTRAINT fk_patient_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT fk_patient_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NULL,
  lead_number VARCHAR(30) NOT NULL,
  name VARCHAR(160) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  phone_normalized VARCHAR(20) NULL,
  alt_phone VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'Other',
  campaign VARCHAR(120) NULL,
  interested_service_id BIGINT UNSIGNED NULL,
  assigned_user_id BIGINT UNSIGNED NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
  status VARCHAR(30) NOT NULL DEFAULT 'New',
  next_followup_at DATETIME NULL,
  notes TEXT NULL,
  converted_patient_id BIGINT UNSIGNED NULL,
  converted_at DATETIME NULL,
  lost_reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_lead_number (organization_id, lead_number),
  KEY idx_lead_phone (organization_id, phone_normalized),
  KEY idx_lead_status (organization_id, status),
  KEY idx_lead_followup (organization_id, next_followup_at),
  KEY idx_lead_assigned (organization_id, assigned_user_id),
  CONSTRAINT fk_lead_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT fk_lead_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE SET NULL,
  CONSTRAINT fk_lead_patient FOREIGN KEY (converted_patient_id) REFERENCES patients (id) ON DELETE SET NULL,
  CONSTRAINT fk_lead_service FOREIGN KEY (interested_service_id) REFERENCES services (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE lead_followups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  lead_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  followup_at DATETIME NOT NULL,
  channel VARCHAR(30) NULL,
  outcome VARCHAR(40) NULL,
  notes TEXT NULL,
  next_followup_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_followup_lead (organization_id, lead_id),
  CONSTRAINT fk_followup_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"ALTER TABLE patients ADD CONSTRAINT fk_patient_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL",

"CREATE TABLE appointments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NOT NULL,
  appointment_number VARCHAR(30) NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  scheduled_at DATETIME NOT NULL,
  duration_minutes INT UNSIGNED NOT NULL DEFAULT 15,
  reason VARCHAR(255) NULL,
  type VARCHAR(40) NOT NULL DEFAULT 'Consultation',
  source VARCHAR(40) NULL,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Scheduled',
  checked_in_at DATETIME NULL,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancel_reason VARCHAR(255) NULL,
  rescheduled_from_id BIGINT UNSIGNED NULL,
  lead_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_appt_number (organization_id, appointment_number),
  KEY idx_appt_doctor_time (organization_id, doctor_id, scheduled_at),
  KEY idx_appt_branch_time (organization_id, branch_id, scheduled_at),
  KEY idx_appt_patient (organization_id, patient_id),
  KEY idx_appt_status (organization_id, status),
  CONSTRAINT fk_appt_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT fk_appt_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE RESTRICT,
  CONSTRAINT fk_appt_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_appt_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE appointment_status_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  appointment_id BIGINT UNSIGNED NOT NULL,
  from_status VARCHAR(30) NULL,
  to_status VARCHAR(30) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  note VARCHAR(255) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_ash_appt (organization_id, appointment_id),
  CONSTRAINT fk_ash_appt FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE queue_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NOT NULL,
  appointment_id BIGINT UNSIGNED NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  queue_date DATE NOT NULL,
  token_number INT UNSIGNED NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'waiting',
  arrived_at DATETIME NOT NULL,
  called_at DATETIME NULL,
  completed_at DATETIME NULL,
  notes VARCHAR(255) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_queue_appt (appointment_id),
  UNIQUE KEY uq_queue_token (organization_id, branch_id, queue_date, token_number),
  KEY idx_queue_day (organization_id, branch_id, queue_date, status),
  KEY idx_queue_doctor (organization_id, doctor_id, queue_date, status),
  CONSTRAINT fk_queue_appt FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
  CONSTRAINT fk_queue_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_queue_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE consultations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NOT NULL,
  appointment_id BIGINT UNSIGNED NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  chief_complaint TEXT NULL,
  symptoms TEXT NULL,
  history TEXT NULL,
  examination TEXT NULL,
  clinical_notes TEXT NULL,
  advice TEXT NULL,
  followup_required TINYINT(1) NOT NULL DEFAULT 0,
  followup_date DATE NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  finalized_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_consult_appt (appointment_id),
  KEY idx_consult_patient (organization_id, patient_id),
  KEY idx_consult_doctor (organization_id, doctor_id, created_at),
  CONSTRAINT fk_consult_appt FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
  CONSTRAINT fk_consult_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
  CONSTRAINT fk_consult_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE diagnoses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  consultation_id BIGINT UNSIGNED NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  code VARCHAR(20) NULL,
  name VARCHAR(200) NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'provisional',
  notes VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_diag_consult (organization_id, consultation_id),
  KEY idx_diag_patient (organization_id, patient_id),
  CONSTRAINT fk_diag_consult FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE vitals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  appointment_id BIGINT UNSIGNED NULL,
  consultation_id BIGINT UNSIGNED NULL,
  height_cm DECIMAL(6,2) NULL,
  weight_kg DECIMAL(6,2) NULL,
  bmi DECIMAL(6,2) NULL,
  temperature_c DECIMAL(5,2) NULL,
  bp_systolic INT UNSIGNED NULL,
  bp_diastolic INT UNSIGNED NULL,
  pulse INT UNSIGNED NULL,
  spo2 INT UNSIGNED NULL,
  respiratory_rate INT UNSIGNED NULL,
  blood_sugar DECIMAL(6,2) NULL,
  blood_sugar_type VARCHAR(20) NULL,
  notes VARCHAR(255) NULL,
  recorded_at DATETIME NOT NULL,
  recorded_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_vitals_patient (organization_id, patient_id, recorded_at),
  KEY idx_vitals_appt (organization_id, appointment_id),
  CONSTRAINT fk_vitals_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
  CONSTRAINT fk_vitals_appt FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE prescriptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NULL,
  consultation_id BIGINT UNSIGNED NOT NULL,
  patient_id BIGINT UNSIGNED NOT NULL,
  doctor_id BIGINT UNSIGNED NOT NULL,
  prescription_number VARCHAR(30) NOT NULL,
  advice TEXT NULL,
  followup_date DATE NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  version INT UNSIGNED NOT NULL DEFAULT 1,
  finalized_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rx_number (organization_id, prescription_number),
  KEY idx_rx_patient (organization_id, patient_id),
  KEY idx_rx_consult (organization_id, consultation_id),
  CONSTRAINT fk_rx_consult FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE CASCADE,
  CONSTRAINT fk_rx_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE prescription_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  prescription_id BIGINT UNSIGNED NOT NULL,
  medicine_name VARCHAR(180) NOT NULL,
  generic_name VARCHAR(180) NULL,
  strength VARCHAR(60) NULL,
  dosage VARCHAR(60) NULL,
  frequency VARCHAR(60) NULL,
  duration VARCHAR(60) NULL,
  timing VARCHAR(60) NULL,
  route VARCHAR(40) NULL,
  instructions VARCHAR(255) NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_rxitem_rx (organization_id, prescription_id),
  CONSTRAINT fk_rxitem_rx FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE prescription_revisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  prescription_id BIGINT UNSIGNED NOT NULL,
  version INT UNSIGNED NOT NULL,
  snapshot LONGTEXT NOT NULL,
  reason VARCHAR(255) NULL,
  changed_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_rx_version (prescription_id, version),
  CONSTRAINT fk_rxrev_rx FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

"CREATE TABLE documents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NULL,
  patient_id BIGINT UNSIGNED NULL,
  entity_type VARCHAR(60) NULL,
  entity_id BIGINT UNSIGNED NULL,
  title VARCHAR(160) NULL,
  file_name VARCHAR(255) NOT NULL,
  stored_path VARCHAR(255) NOT NULL,
  mime VARCHAR(120) NULL,
  size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
  uploaded_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_doc_patient (organization_id, patient_id),
  KEY idx_doc_entity (organization_id, entity_type, entity_id),
  CONSTRAINT fk_doc_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ],
];
